name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy-documentation:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    # Step 3: Cache Python dependencies
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-python-${{ hashFiles('requirements.txt') }}
        path: .cache

    # Step 4: Install Python dependencies
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install requests

    # Step 5: Validate internal and external links in Markdown
    - name: Validate internal and external links in Markdown
      run: python .github/scripts/validate_internal_external_links.py

    # Step 6: Validate image links in Markdown
    - name: Validate image links in Markdown
      run: python .github/scripts/validate_images.py

    # Step 7: Build English Documentation
    - name: Build English Documentation
      run: mkdocs build -f config/en/mkdocs.yml

    # Step 8: Build German Documentation
    - name: Build German Documentation
      run: mkdocs build -f config/de/mkdocs.yml

    # Step 9: Copy common root files (including legacy redirects)
    - name: Copy common root files (including legacy redirects)
      run: cp -R docs/root/* site

    # Step 10: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master' && success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
